name: Continuous Deployment

on: [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest 
    steps:
            - uses: actions/checkout@v2
            
            - name: AWS SSM Send Command
              uses: peterkimzz/aws-ssm-send-command@1.0.1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
                  #aws-access-key-id: 854414654821

                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
                  #aws-secret-access-key: AKIA4N3YU7VSU6OUTO6G
                  aws-region: us-east-1b
                  instance-ids: ${{ secrets.INSTANCE_ID  }}
                  #instance-ids: i-0695f155347c85262
                  comment: Deploy the master branch
                  working-directory: /home/ubuntu/personal_websites
                  #command: /bin/sh ./deploy.sh
                  command: sudo git pull origin master
